#!/usr/bin/env bash
# This script tells a story based on /etc/passwd
filepath="/etc/passwd"
while IFS=":" read -r USERNAME GROUP_ID HOME_DIRECTORY COMMAND USERID PASSWORD USERIDINFO
do 
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USERID place is protected by the passcode $PASSWORD, more info about the user here: $USERIDINFO"

done < $filepath
