#!/usr/bin/env bash
# This script displays the same thing 10 Times
x=1
while [ $x -le 20 ] 
do 
	if [ $x == 4 ] 
	then 
		echo "$x bad luck from China"
	elif [ $x == 9 ] 
	then 
		echo "$x bad luck from Japan"
	elif [ $x == 17 ]
	then
		echo "$x bad luck from Italy"
	else
		echo "$x"
	fi
	x=$((x+1))       
done
