#!/usr/bin/env bash
# This script displays the same thing 10 Times
x=1
while [ $x -le 20 ] 
do 
	echo "$x"
	case $x in
		"4")
			echo "bad luck from China"
			;;
		"8")
			echo "bad luck from Japan"
			;;
		"17")
			echo "bad luck from Italy"
			;;
	esac
	x=$((x+1))       
done
