#!/usr/bin/env bash
# Kills other loop
case $1 in
	start)
		./manage_my_process &
		echo $! >> /var/run/my_process.pid &
		echo "manage_my_process started"
		;;
	stop) 
		rm /var/run/my_process.pid &
		echo "manage_my_process stopped"
		;;
	restart)
		rm /var/run/my_process.pid &
		./manage_my_process &
		echo $! >> /var/run/my_process.pid &
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process (start|stop|restart)"
		;;
esac
