#!/usr/bin/env bash
# Kills other loop
case $1 in
	start)
		./manage_my_process
		echo pidof manage_my_process | sudo tee /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		sudo kill "$(pgrep -f manage_my_process)" 
		sudo rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		sudo kill "$(pgrep -f manage_my_process)"
		sudo rm /var/run/my_process.pid
		./manage_my_process
		echo pidof manage_my_process | sudo tee /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process (start|stop|restart)"
		;;
esac
