#!/usr/bin/env bash
#dalsdf;j
case $1 in
	start)
		./manage_my_process &
		echo "$1" > idontlikeyou
	;;
	stop)
		echo "$1"
		./doubtful
	;;
	restart)
		echo "$1"
		./asifiwould
	;;
	*)
		echo "$1"
		./hediditthough
	;;
esac
